spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: 77492652Rt@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 8085

stripe:
  api:
    key: sk_test_51RYWLQ01DT1tOG6qpAKR4LCz8ZDTtLCxUdT7tUPWpElSdXAAjIBGgd56LlWUDUi0rRm3cKnjCasauZAe4fU7yvbR00RuTyjjVr

logging:
  level:
    org.springframework: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      cropClientBreaker:
        slidingWindowSize: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 2
      orderClientBreaker:
        slidingWindowSize: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 2
      notificationClientBreaker:
        slidingWindowSize: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 2

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

feign:
  circuitbreaker:
    enabled: true
